task: detection

num_classes: 80
remap_mscoco_category: True

train_dataloader: 
  type: DataLoader
  dataset: 
    type: CocoDetection
    img_folder: D:\My_passport\Python\Project\2024.11.6 RT-DETR\coco\train2017
    ann_file: D:\My_passport\Python\Project\2024.11.6 RT-DETR\coco\annotations\instances_train2017.json
    transforms:
      type: Compose
      ops: ~
  shuffle: True
  batch_size: 2
  num_workers: 1
  drop_last: True 


val_dataloader:
  type: DataLoader
  dataset: 
    type: CocoDetection
    img_folder: D:\My_passport\Python\Project\2024.11.6 RT-DETR\coco\val2017
    ann_file: D:\My_passport\Python\Project\2024.11.6 RT-DETR\coco\annotations\instances_val2017.json
    transforms:
      type: Compose
      ops: ~ 

  shuffle: False
  batch_size: 8
  num_workers: 1
  drop_last: False